/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista_VentanaAdministrarEmpleados;

import Conector_FireBase.ConectorFireBase;
import java.awt.Color;
import java.awt.Image;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author USUARIO
 */
public class subVentanaEmpleado extends javax.swing.JFrame {

    private String idEmpleado;
    private VentanaAdministrarEmpleados ventanaPadre;

    public subVentanaEmpleado(VentanaAdministrarEmpleados ventanaPadre, String[] dataRow) {
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);

        this.idEmpleado = dataRow[0];
        this.ventanaPadre = ventanaPadre;

        labelID.setText("Datos del empleado " + dataRow[0]);

        txtApellidos.setText(dataRow[1]);
        txtNombres.setText(dataRow[2]);
        cbCargo.setSelectedItem(dataRow[3]);
        spinnerSueldo.setValue(Integer.parseInt(dataRow[4]));
        txtNumeroCelular.setText(dataRow[5]);
        txtCorreoElectronico.setText(dataRow[6].split("@")[0]);

        //Deteccion de ventana cerrada
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                ventanaPadre.ventanaCerrada();
            }
        });

        botonActualizarDatos.setIcon(setIcono("/iconos/actualizarEmpleado.png", botonActualizarDatos));
        botonEliminarEmpleado.setIcon(setIcono("/iconos/eliminarEmpleado.jpg", botonEliminarEmpleado));

    }

    public Icon setIcono(String url, JButton boton) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));

        int ancho = boton.getWidth();
        int alto = boton.getHeight();

        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));

        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtApellidos = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtCorreoElectronico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroCelular = new javax.swing.JTextField();
        botonActualizarDatos = new javax.swing.JButton();
        botonEliminarEmpleado = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbTipoCorreo = new javax.swing.JComboBox<>();
        cbCargo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        spinnerSueldo = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApellidos.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidos.setMargin(new java.awt.Insets(2, 7, 2, 7));
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 120, 24));

        txtNombres.setBackground(new java.awt.Color(255, 255, 255));
        txtNombres.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(0, 0, 0));
        txtNombres.setMargin(new java.awt.Insets(2, 7, 2, 7));
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, 24));

        txtCorreoElectronico.setBackground(new java.awt.Color(255, 255, 255));
        txtCorreoElectronico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCorreoElectronico.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreoElectronico.setMargin(new java.awt.Insets(2, 7, 2, 7));
        jPanel1.add(txtCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 220, 210, 24));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Apellidos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombres");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cargo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("E-mail");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Teléfono");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Sueldo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        txtNumeroCelular.setBackground(new java.awt.Color(255, 255, 255));
        txtNumeroCelular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNumeroCelular.setForeground(new java.awt.Color(0, 0, 0));
        txtNumeroCelular.setMargin(new java.awt.Insets(2, 7, 2, 7));
        jPanel1.add(txtNumeroCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 120, 24));

        botonActualizarDatos.setBackground(new java.awt.Color(255, 255, 255));
        botonActualizarDatos.setBorder(null);
        botonActualizarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarDatosActionPerformed(evt);
            }
        });
        jPanel1.add(botonActualizarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 100, 100));

        botonEliminarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        botonEliminarEmpleado.setBorder(null);
        botonEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(botonEliminarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 100, 100));

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        labelID.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelID.setForeground(new java.awt.Color(255, 255, 255));
        labelID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelID.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 80));

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Eliminar empleado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Actualizar datos");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        cbTipoCorreo.setBackground(new java.awt.Color(255, 255, 255));
        cbTipoCorreo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        cbTipoCorreo.setForeground(new java.awt.Color(0, 0, 0));
        cbTipoCorreo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "@gmail.com", "@hotmail.com", "@outlook.com" }));
        jPanel1.add(cbTipoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 220, 120, 24));

        cbCargo.setBackground(new java.awt.Color(255, 255, 255));
        cbCargo.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        cbCargo.setForeground(new java.awt.Color(0, 0, 0));
        cbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cargo 1", "Cargo 2", "Cargo 3", "Cargo 4" }));
        jPanel1.add(cbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 120, 24));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("S/.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 24, 24));

        spinnerSueldo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        spinnerSueldo.setModel(new javax.swing.SpinnerNumberModel(0, null, null, 100));
        spinnerSueldo.setToolTipText("");
        jPanel1.add(spinnerSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 100, 24));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarEmpleadoActionPerformed
        eliminarEmpleado();
        ventanaPadre.ventanaCerrada();
        ventanaPadre.ventanaCerrada();
        this.dispose();
    }//GEN-LAST:event_botonEliminarEmpleadoActionPerformed

    private void botonActualizarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarDatosActionPerformed
        actualizarEmpleado();
    }//GEN-LAST:event_botonActualizarDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarDatos;
    private javax.swing.JButton botonEliminarEmpleado;
    private javax.swing.JComboBox<String> cbCargo;
    private javax.swing.JComboBox<String> cbTipoCorreo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelID;
    private javax.swing.JSpinner spinnerSueldo;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumeroCelular;
    // End of variables declaration//GEN-END:variables

    private void eliminarEmpleado() {
        ConectorFireBase.eliminarEmpleado("Empleados", idEmpleado);
    }

    private void actualizarEmpleado() {
        Map<String, Object> datos = new HashMap<>();

        //VALIDACION DE DATOS
        int errores = 0;
        errores += validacionTxtNormales(txtNombres);
        errores += validacionTxtNormales(txtApellidos);
        errores += validacionTxtNormales(txtCorreoElectronico);
        errores += validacionTxtNumeroCelular(txtNumeroCelular);
        errores += validacionSpinnerSueldo(spinnerSueldo);

        if (errores == 0) {
            //GUARDA LOS DATOS A ENVIAR
            datos.put("apellidos", txtApellidos.getText().trim());
            datos.put("nombres", txtNombres.getText().trim());
            datos.put("cargo", cbCargo.getSelectedItem().toString().trim());
            datos.put("sueldo", spinnerSueldo.getValue().toString().trim());
            datos.put("numero_celular", txtNumeroCelular.getText().trim());
            datos.put("correo_electronico", txtCorreoElectronico.getText().trim() + cbTipoCorreo.getSelectedItem().toString().trim());

            //ENVIA LOS DATOS A LA BASE DE DATOS
            ConectorFireBase.actualizarEmpleado("Empleados", idEmpleado, datos);
        } else {
            JOptionPane.showMessageDialog(null, "Uno o mas datos ingresados son incorrectos, revíselo y reintente nuevamente");
            reiniciarFondos();
        }

    }

    private int validacionTxtNormales(JTextField txt) {

        if ("".equals(txt.getText())) {
            txt.setBackground(Color.red);
            return 1;
        } else {
            return 0;
        }

    }

    private int validacionTxtNumeroCelular(JTextField txt) {
        if (txt.getText().length() != 9) {
            txt.setBackground(Color.red);
            return 1;
        } else if (txt.getText().startsWith("9")) {
            return 0;
        } else {
            txt.setBackground(Color.red);
            return 1;
        }
    }

    private int validacionSpinnerSueldo(JSpinner spinner) {
        if ((int) spinner.getValue() == 0) {
            return 1;
        } else {
            return 0;
        }
    }

    private void reiniciarCampos() {
        txtApellidos.setText("");
        txtNombres.setText("");
        spinnerSueldo.setValue(0);
        txtNumeroCelular.setText("");
        txtCorreoElectronico.setText("");
        cbTipoCorreo.setSelectedIndex(0);
        cbCargo.setSelectedIndex(0);
    }

    private void reiniciarFondos() {
        txtNombres.setBackground(Color.white);
        txtApellidos.setBackground(Color.white);
        txtNumeroCelular.setBackground(Color.white);
        txtCorreoElectronico.setBackground(Color.white);
    }
}
